# BattleNight Version: 2.0
# Classes Configuration File
#
# Add Classes as you wish but do not use spaces in names.
# Items are i:dxa, i=Item d=data a=Amount.  Data and amount are optional

Classes:
    Pyro:
        Armour: 298, 299, 300, 301
        Items: 259, 46x2, 373:8195
    Tank:
        Armor: 310, 311, 312, 313
        Items: 272
    Swordsman:
        Armor: 306, 307, 308, 309
        Items: 276e(16~5|19~2), 373:8233
    Archer:
        Armor: 302, 303, 304, 305
        Items: 261, 262x128
    Medic:
        Armor: 298, 303, 304, 305
        Items: 283, 322x4, 373:16389, 373:16389, 373:16385
    Magician:
        Armor: none
        Items: 268, 373:8258, 373:16388, 373:16392, 373:16394, 373:16396
        
        