en:
    Commands:
        NoPermission:       '&cYou do not have permission to perform this command.'
        PlayerOnly:         '&cThis command can only be run by a Player.'
        InvalidCommand:     '&cInvalid Command.  Type "/bn help" for help.'
        PlayerNotFound:     '&cThe player "<arg0>" was not found.'