# BattleNight Version ${project.version}
# Tracks Configuration
#
# You may edit this but it is not recommended as it could cause confusion.

en:
    Commands:
        NoPermission:       '&cYou do not have permission to perform this command.'
        PlayerOnly:         '&cThis command can only be run by a Player.'
        InvalidCommand:     '&cInvalid Command.  Type "/bn help" for help.'
        PlayerNotFound:     '&cThe player "<arg0>" was not found.'
        InvalidWaypoint:    '&cInvalid Waypoint.'
        GlobalWaypointSet:  'Global Waypoint "<arg0>" set.'
        ArenaWaypointSet:   'Waypoint "<arg0>" set for Arena "<arg1>".'