name: ${project.name}
author: LimeByte
version: ${project.version}
description: ${project.description}

main: me.limebyte.battlenight.core.BattleNight
load: POSTWORLD

website: ${project.url}
dev-url: http://dev.bukkit.org/server-mods/battlenight/
database: false

commands:
  bn:
    description: Base command for the BattleNight plug-in.
    aliases: [battlenight, battleknight, bnight]
    usage: |
        /<command> help - Show the help menu
        
permissions:
    battlenight.user:
        description: Allows you to use user commands.
        default: true
    battlenight.moderator:
        description: Allows you to use moderator commands.
        default: op
    battlenight.admin:
        description: Allows you to use admin commands.
        default: op
        
    battlenight.*:
        description: Gives you all BattleNight permissions.
        default: false
        children:
            battlenight.user: true
            battlenight.admin: true
            battlenight.moderator: true